GET http://localhost:3001/users/faculty/420
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODYyMjA0MDcsIm5iZiI6MTU4NjIyMDQwNywianRpIjoiNWQ3MTM1YWEtNmYzMy00NzQwLTgyZGItZDliZDZkMzU3NGJmIiwiZXhwIjoxNjQwNjUyNDA3LCJpZGVudGl0eSI6eyJjb3JyZW8iOiJqdWFuZXNjaHJvbWVAZ21haWwuY29tIiwibm9tYnJlIjoiSlVBTiBFU1RFQkFOIFFVSU5URVJPIiwiY2xhdmUiOiJkMTgwMzc2YTVlOTQ3YzdjOGI1ZTUwMzk0OTMyOTcyYSIsInJvbCI6IkFkbWluIiwicHJvZ3JhbWEiOm51bGwsImZhY3VsdGFkIjpudWxsfSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.tSf8BjrFNv9eFfQ8liHQpxlESGWOoeJQ_RODSi0SaSw