GET http://localhost:3001/sets
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjM5MzMxNywianRpIjoiOTExMWFjMmMtOTNhYS00ODlmLTlkNjUtMjhmMmFiOWMxMzlhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJyb2wiOiJBZG1pbiIsIm5vbWJyZSI6IlNVUEVSIEFETUlOIiwiY2xhdmUiOiIyNWQ1NWFkMjgzYWE0MDBhZjQ2NGM3NmQ3MTNjMDdhZCIsImNvcnJlbyI6ImFkbWluQHBsZXlhZGVzLmNvbSJ9LCJuYmYiOjE3MjIzOTMzMTcsImNzcmYiOiJhOTI2MjdhZi0xNTQ1LTRhOTQtYjQzZC1lN2MzOWNhYjFjNTMiLCJleHAiOjE3MjI0MDA1MTd9.u3PO3U1y8UONHWfOY9RNprxx7OCrXNC_U6OjD7hIGZE

###

GET http://localhost:3001/sets/estado/crudos
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjM5MzMxNywianRpIjoiOTExMWFjMmMtOTNhYS00ODlmLTlkNjUtMjhmMmFiOWMxMzlhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJyb2wiOiJBZG1pbiIsIm5vbWJyZSI6IlNVUEVSIEFETUlOIiwiY2xhdmUiOiIyNWQ1NWFkMjgzYWE0MDBhZjQ2NGM3NmQ3MTNjMDdhZCIsImNvcnJlbyI6ImFkbWluQHBsZXlhZGVzLmNvbSJ9LCJuYmYiOjE3MjIzOTMzMTcsImNzcmYiOiJhOTI2MjdhZi0xNTQ1LTRhOTQtYjQzZC1lN2MzOWNhYjFjNTMiLCJleHAiOjE3MjI0MDA1MTd9.u3PO3U1y8UONHWfOY9RNprxx7OCrXNC_U6OjD7hIGZE

###

GET http://localhost:3001/sets/estado/procesados
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjM5MzMxNywianRpIjoiOTExMWFjMmMtOTNhYS00ODlmLTlkNjUtMjhmMmFiOWMxMzlhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJyb2wiOiJBZG1pbiIsIm5vbWJyZSI6IlNVUEVSIEFETUlOIiwiY2xhdmUiOiIyNWQ1NWFkMjgzYWE0MDBhZjQ2NGM3NmQ3MTNjMDdhZCIsImNvcnJlbyI6ImFkbWluQHBsZXlhZGVzLmNvbSJ9LCJuYmYiOjE3MjIzOTMzMTcsImNzcmYiOiJhOTI2MjdhZi0xNTQ1LTRhOTQtYjQzZC1lN2MzOWNhYjFjNTMiLCJleHAiOjE3MjI0MDA1MTd9.u3PO3U1y8UONHWfOY9RNprxx7OCrXNC_U6OjD7hIGZE


###

GET http://localhost:3001/sets/estado/en proceso
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTcyMjM5MzMxNywianRpIjoiOTExMWFjMmMtOTNhYS00ODlmLTlkNjUtMjhmMmFiOWMxMzlhIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6eyJyb2wiOiJBZG1pbiIsIm5vbWJyZSI6IlNVUEVSIEFETUlOIiwiY2xhdmUiOiIyNWQ1NWFkMjgzYWE0MDBhZjQ2NGM3NmQ3MTNjMDdhZCIsImNvcnJlbyI6ImFkbWluQHBsZXlhZGVzLmNvbSJ9LCJuYmYiOjE3MjIzOTMzMTcsImNzcmYiOiJhOTI2MjdhZi0xNTQ1LTRhOTQtYjQzZC1lN2MzOWNhYjFjNTMiLCJleHAiOjE3MjI0MDA1MTd9.u3PO3U1y8UONHWfOY9RNprxx7OCrXNC_U6OjD7hIGZE

###


