GET http://localhost:3001/usuarios
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1OTU3ODI2NjAsIm5iZiI6MTU5NTc4MjY2MCwianRpIjoiMTQ1YjNmMzctZGMyYS00NDkxLTgxYWUtOTZjMWE4YzY0NWJhIiwiZXhwIjoxNTk1Nzg5ODYwLCJpZGVudGl0eSI6eyJjb3JyZW8iOiJhZG1pbkBwbGV5YWRlcy5jb20iLCJub21icmUiOiJTVVBFUiBBRE1JTiIsImNsYXZlIjoiMjVkNTVhZDI4M2FhNDAwYWY0NjRjNzZkNzEzYzA3YWQiLCJyb2wiOiJBZG1pbiJ9LCJmcmVzaCI6ZmFsc2UsInR5cGUiOiJhY2Nlc3MifQ.n5Rpbn_Joii7MM-6jaKmL5SLyfVs-pZXFC8lf3OLaVQ

###

GET http://localhost:3001/usuarios/admin@pleyades.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODYyMjA0MDcsIm5iZiI6MTU4NjIyMDQwNywianRpIjoiNWQ3MTM1YWEtNmYzMy00NzQwLTgyZGItZDliZDZkMzU3NGJmIiwiZXhwIjoxNjQwNjUyNDA3LCJpZGVudGl0eSI6eyJjb3JyZW8iOiJqdWFuZXNjaHJvbWVAZ21haWwuY29tIiwibm9tYnJlIjoiSlVBTiBFU1RFQkFOIFFVSU5URVJPIiwiY2xhdmUiOiJkMTgwMzc2YTVlOTQ3YzdjOGI1ZTUwMzk0OTMyOTcyYSIsInJvbCI6IkFkbWluIiwicHJvZ3JhbWEiOm51bGwsImZhY3VsdGFkIjpudWxsfSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.tSf8BjrFNv9eFfQ8liHQpxlESGWOoeJQ_RODSi0SaSw


###


POST http://localhost:3001/usuarios/
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODYyMjA0MDcsIm5iZiI6MTU4NjIyMDQwNywianRpIjoiNWQ3MTM1YWEtNmYzMy00NzQwLTgyZGItZDliZDZkMzU3NGJmIiwiZXhwIjoxNjQwNjUyNDA3LCJpZGVudGl0eSI6eyJjb3JyZW8iOiJqdWFuZXNjaHJvbWVAZ21haWwuY29tIiwibm9tYnJlIjoiSlVBTiBFU1RFQkFOIFFVSU5URVJPIiwiY2xhdmUiOiJkMTgwMzc2YTVlOTQ3YzdjOGI1ZTUwMzk0OTMyOTcyYSIsInJvbCI6IkFkbWluIiwicHJvZ3JhbWEiOm51bGwsImZhY3VsdGFkIjpudWxsfSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.tSf8BjrFNv9eFfQ8liHQpxlESGWOoeJQ_RODSi0SaSw
Content-Type: application/json

{
  "nombre": "JUANES QUINTERO",
  "correo": "juanes@gmail.com",
  "clave": "81dc9bdb52d04dc20036dbd8313ed055",
  "rol": "Admin"
}

###

PUT http://localhost:3001/usuarios/juanes@gmail.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODYyMjA0MDcsIm5iZiI6MTU4NjIyMDQwNywianRpIjoiNWQ3MTM1YWEtNmYzMy00NzQwLTgyZGItZDliZDZkMzU3NGJmIiwiZXhwIjoxNjQwNjUyNDA3LCJpZGVudGl0eSI6eyJjb3JyZW8iOiJqdWFuZXNjaHJvbWVAZ21haWwuY29tIiwibm9tYnJlIjoiSlVBTiBFU1RFQkFOIFFVSU5URVJPIiwiY2xhdmUiOiJkMTgwMzc2YTVlOTQ3YzdjOGI1ZTUwMzk0OTMyOTcyYSIsInJvbCI6IkFkbWluIiwicHJvZ3JhbWEiOm51bGwsImZhY3VsdGFkIjpudWxsfSwiZnJlc2giOmZhbHNlLCJ0eXBlIjoiYWNjZXNzIn0.tSf8BjrFNv9eFfQ8liHQpxlESGWOoeJQ_RODSi0SaSw
Content-Type: application/json

{
  "nombre": "JHONNY ALBERT PEREZ",
  "clave": "12345678",
  "rol": "Analista"
}


###


DELETE http://localhost:3001/usuarios/juanes@gmail.com
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE1ODYyMjA0MDcsIm5iZiI6MTU4NjIyMDQwNywianRpIjoiNWQ3MTM1YWEtNmYzMy00NzQwLTgyZGItZDliZDZkMzU3NGJmIiwiZXhwIjoxNjQwNjUyNDA3LCJpZGVudGl0eSI6eyJjb3JyZW8i

