# Gitlab CI/CD Variables needed for this pipeline


stages:
  - test
  - build
  - deploy

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - echo "Starting pipeline..."
  - echo "Logging in to AWS..."

web-test:
  stage: test
  image: python:3.12-slim
  script:
    - echo "Testing web app..."

api-test:
  stage: test
  image: python:3.12-slim
  script:
    - echo "Testing api app..."

apps-build:
  stage: build
  image: python:3.12-slim
  script:
    - echo "Building app..."

server-deploy:
  stage: deploy
  image:
    name: amazon/aws-cli:2.15.19
    entrypoint: ["/bin/bash", "-c"]
  script:
    - echo "Deploying to AWS EC2..."
  when: manual

serverless-deploy:
  stage: deploy
  image:
    name: amazon/aws-cli:2.15.19
    entrypoint: ["/bin/bash", "-c"]
  script:
    - echo "Deploying to AWS Lambda..."
  when: manual


.global_rules:
  rules:
    - if: '$CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main" || $CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "develop"'
