version: '3.8'
services:

  dev:
    container_name: pleyades-web
    build:
      context: ./web
      dockerfile: ./Dockerfile
    image: pleyades-web:1.0.0
    volumes:
      - ./web:/app
    networks:
      - dev-net
    env_file:
      - ./web/.env
    environment:
      - FLASK_ENV=development
      - FLASK_APP=__init__:app
      - FLASK_DEBUG=1
      - TEMPLATES_AUTO_RELOAD=1
    ports:
      - 5000:80
    command: flask run --host 0.0.0.0 --port 80
  
  prod:
    container_name: pleyades-web
    build:
      context: ./web
      dockerfile: ./Dockerfile
    image: pleyades-web:1.0.0
    volumes:
      - ./web:/app
    env_file:
      - ./web/.env
    environment:
      - FLASK_ENV=production
      - FLASK_APP=__init__:app
    ports:
      - 80:80
    command: gunicorn run:app --bind 0.0.0.0:80 --workers 3

networks:
  dev-net:
    driver: bridge

