version: "3.8"
name: pleyades-dev
services:
  
  web:
    container_name: pleyades-web_dev
    build:
      context: ./web
      dockerfile: ./Dockerfile
    image: pleyades-web:1.0.0
    volumes:
      - ./ies.json:/app/ies.json
      - ./web:/app
    env_file:
      - ./web/.env
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=__init__:app
      - TEMPLATES_AUTO_RELOAD=1
      - CLI_IES_NAME=${PLEYADES_IES_CLIENT}
    ports:
      - 5000:80
    networks:
      - dev-net
    depends_on:
      - api
    command: flask run --host 0.0.0.0 --port 80

  api:
    container_name: pleyades-api_dev
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: pleyades-api:1.0.0
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=__init__:app
      - CLI_IES_NAME=${PLEYADES_IES_CLIENT}
    ports:
      - 3000:80
    networks:
      dev-net:
        aliases:
          - api-host
    depends_on:
      - db
    command: flask run --host 0.0.0.0 --port 80

  db:
    container_name: pleyades-db_dev
    image: mysql:8.0.3
    cap_add:
      - SYS_NICE
    restart: always
    env_file:
      - ./api/.env
    environment:
      - MYSQL_ROOT_PASSWORD=${PLEYADES_MYSQL_ROOT_PASSWORD}
    volumes:
      - ./api/db/pleyades/dev:/var/lib/mysql
      - ./api/db/pleyades/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      dev-net:
        aliases:
          - db-host


  adminer:
    container_name: pleyades-adminer
    image: adminer:4
    ports:
      - 8080:8080
    links:
      - db:db
    networks:
      - dev-net
      - pleyades-prod_deploy-net

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-CU3-ubuntu-18.04
    user: '0:0'
    container_name: sqlserver2019
    ports:
      - 1433:1433
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: PasswordO1.
      MSSQL_PID: Express
    volumes:
      # - ~/docker/sqlserver-data:/var/opt/mssql
      - ./sqlserver-data:/var/opt/mssql

networks:
  dev-net:
    driver: bridge
  pleyades-prod_deploy-net:
    external: true
