name: pleyades

services:

  nginx:
    restart: always
    image: nginx:1.27-alpine-slim
    container_name: pleyades-nginx
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/snippets/proxy_params:/etc/nginx/proxy_params
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx/logs:/var/log/nginx
      - ./nginx/www:/var/www
    environment:
      - CLI_IES_NAME=${IES_CLIENT}
    ports:
      - ${PUBLIC_PORT}:80
    networks:
      - deploy-net
    links:
      - web:web
      - api:api
    depends_on:
      - web

  web:
    restart: always
    container_name: pleyades-web
    build:
      context: ./web
      dockerfile: ./Dockerfile
    image: pleyades-web:1.0.0
    volumes:
      - ./web:/app
      - ./ies.json:/app/ies.json
    env_file:
      - ./web/.env
    environment:
      - FLASK_DEBUG=0
      - FLASK_APP=__init__:app
      - CLI_IES_NAME=${IES_CLIENT}
    networks:
      - deploy-net
    links:
      - api:api
    command: gunicorn __init__:app --preload --bind 0.0.0.0:80 --workers 3 --timeout=5400
    depends_on:
      - api

  api:
    restart: always
    container_name: pleyades-api
    build:
      context: ./api
      dockerfile: ./Dockerfile
    image: pleyades-api:1.0.0
    env_file:
      - ./api/.env
    environment:
      - FLASK_DEBUG=0
      - FLASK_APP=__init__:create_app()
      - CLI_IES_NAME=${IES_CLIENT}
    volumes:
      - ./api:/app
    networks:
      - deploy-net
    command: gunicorn wsgi:app --bind 0.0.0.0:80 --workers 3 --timeout=5400

networks:
  deploy-net:
    driver: bridge
