name: pleyades

services:
  web:
    container_name: pleyades-web_dev
    restart: on-failure
    image: pleyades-web:1.0.0
    build:
      context: ./web
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - ./ies.json:/app/ies.json
      - ./web:/app
    env_file:
      - ./web/.env
    environment:
      - CLI_IES_NAME=${IES_CLIENT}
    ports:
      - 5001:80
      - 5678:5678
    links:
      - api
      - redis
    networks:
      - dev-net
    depends_on:
      - api
      - celery
    command: python -m debugpy --listen 0.0.0.0:5678 --wait-for-client run.py  
    # python run.py --celery

  api:
    container_name: pleyades-api_dev
    restart: on-failure
    image: pleyades-api:1.0.0
    build:
      context: ./api
      dockerfile: ./Dockerfile
      target: development
    volumes:
      - ./api:/app
    env_file:
      - ./api/.env
    environment:
      - FLASK_DEBUG=1
      - FLASK_APP=run.py
      - CLI_IES_NAME=${IES_CLIENT}
    ports:
      - 8001:80
      - 5679:5679
    links:
      - db
      - db-ies
    networks:
      - dev-net
    depends_on:
      - db
    command: python -m debugpy --listen 0.0.0.0:5679 --wait-for-client run.py --celery

  celery:
    container_name: pleyades-celery
    restart: on-failure
    image: pleyades-web:1.0.0
    volumes:
      - ./ies.json:/app/ies.json
      - ./web:/app
    env_file:
      - ./web/.env
    environment:
      - CLI_IES_NAME=${IES_CLIENT}
    links:
      - redis
    networks:
      - dev-net
      - deploy-net
    depends_on:
      - redis
    command: python run.py --celery

  redis:
    container_name: pleyades-redis
    restart: on-failure
    image: redis:latest
    volumes:
      - ./redis_data:/data
    networks:
      - dev-net
      - deploy-net

  db:
    container_name: pleyades-db
    restart: on-failure
    image: mysql:8.0.3
    cap_add:
      - SYS_NICE
    env_file:
      - ./api/.env
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PWD}
    volumes:
      - ./api/db/pleyades/dev:/var/lib/mysql
      - ./api/db/pleyades/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - dev-net
      - deploy-net

  db-ies:
    container_name: pleyades-db-ies
    restart: on-failure
    image: pleyades-db-ies:1.0.0
    build:
      context: ./api/db/ies
      dockerfile: ./Dockerfile
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$MSSQL_SA_PASSWORD" -Q "SELECT 1"
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 1433:1433
    env_file:
      - ./api/db/ies/.env
    volumes:
      - ./api/db/ies/sqlserver-data:/var/opt/mssql
    networks:
      - dev-net
      - deploy-net

  adminer:
    container_name: pleyades-adminer
    restart: on-failure
    image: adminer:4.8.1
    ports:
      - 8080:8080
    links:
      - db
      - db-ies
    networks:
      - dev-net

networks:
  dev-net:
    driver: bridge

  deploy-net:
    driver: bridge
