-- Database & User definition
USE [master]

CREATE DATABASE $(MSSQL_DBNAME);
GO


USE [$(MSSQL_DBNAME)]
GO

CREATE LOGIN $(MSSQL_DBUSER) WITH PASSWORD = '$(MSSQL_DBUSERPWD)';
CREATE USER $(MSSQL_DBUSER) FOR LOGIN $(MSSQL_DBUSER);
GRANT SELECT, INSERT, UPDATE, DELETE ON SCHEMA::dbo TO $(MSSQL_DBUSER);

GO
