-- Database & User definition
USE [master]
GO IF NOT EXISTS (
    SELECT *
    FROM sys.databases
    WHERE name = '$(MSSQL_DBNAME)'
  ) BEGIN CREATE DATABASE $(MSSQL_DBNAME);
END;
GO USE [$(MSSQL_DBNAME)]
GO IF NOT EXISTS (
    SELECT *
    FROM sys.sysusers
    WHERE name = '$(MSSQL_DBUSER)'
  ) BEGIN CREATE LOGIN $(MSSQL_DBUSER) WITH PASSWORD = '$(MSSQL_DBUSERPWD)';
CREATE USER $(MSSQL_DBUSER) FOR LOGIN $(MSSQL_DBUSER);
GRANT SELECT,
  INSERT,
  UPDATE,
  ALTER,
  DELETE ON SCHEMA::dbo TO $(MSSQL_DBUSER);
GRANT CREATE TABLE TO $(MSSQL_DBUSER);
END