@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmcmVzaCI6ZmFsc2UsImlhdCI6MTc0MjQwMjU4MiwianRpIjoiYWU2Y2NjYTgtZWE3NS00ZmI0LTk0YzAtNjc1NzdjMDA3MjAzIiwidHlwZSI6ImFjY2VzcyIsInN1YiI6InsnZW1haWwnOiAnYWRtaW5AcGxleWFkZXMuY29tJywgJ25hbWUnOiAnU1VQRVIgQURNSU4nLCAncm9sZSc6ICdBZG1pbicsICdwYXNzd29yZCc6ICcyNWQ1NWFkMjgzYWE0MDBhZjQ2NGM3NmQ3MTNjMDdhZCd9IiwibmJmIjoxNzQyNDAyNTgyLCJjc3JmIjoiYjA4ODY3NzItYTk5NC00NjU5LTk1YmMtODRlM2FmZmExNTBiIiwiZXhwIjoxNzQyNDEzMzgyfQ.emAJ96HwqhUaiZaMEKKVvz4Mwe9vVCogp1aLEOp-qes

###

GET http://localhost:8001/preparations
Authorization: Bearer {{token}}

###

GET http://localhost:8001/preparations/1
Authorization: Bearer {{token}}

###

